### ISSUE TITLE
not able to run server

### ISSUE THREAD

**Issue by vnitinv** [bkayser/thrift-versioning-doc#3]
I am new to ruby (or my first day to it).
I tried with all the steps you mentioned. I am getting some SyntexError from server.rb
Find the log below. Whats the issue?

$ rackup
/xxx/thrift-versioning-doc/examples/config.ru:2:in `load': ./server.rb:21: syntax error, unexpected ':', expecting kEND (SyntaxError)
...vices::V1::AccountID.new name: name, id: id, parent: 1
                              ^
./server.rb:21: syntax error, unexpected ':', expecting '='
...:AccountID.new name: name, id: id, parent: 1
                              ^
./server.rb:21: syntax error, unexpected ':', expecting '='
...ew name: name, id: id, parent: 1
                              ^
./server.rb:31: syntax error, unexpected ':', expecting kEND
...vices::V2::AccountID.new name: name, id: id, parent: 1
                              ^
./server.rb:31: syntax error, unexpected ':', expecting '='
...:AccountID.new name: name, id: id, parent: 1
                              ^
./server.rb:31: syntax error, unexpected ':', expecting '='
...ew name: name, id: id, parent: 1

**Comment by bkayser** [comment]
Looks like you have an old version of Ruby.  Try running it with 2.*.
